server:
  port: 8000

spring:
  application:
    name: Engage Code Challenge

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  # Data source configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/engagecc
    driver-class-name: org.postgresql.Driver
    username: engagecc
    password: password
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    info:
      enabled: true